# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Xilinx_Embedded_Design/Xilinx_Embedded_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Xilinx_Embedded_Design || ORIG_REF_NAME==Xilinx_Embedded_Design} -quiet] -quiet

# IP: bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/Xilinx_Embedded_Design/Xilinx_Embedded_Design_ooc.xdc
