# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.cache/wt [current_project]
set_property parent.project_path /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_output_repo /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/hdl/Xilinx_Embedded_Design_wrapper.v
add_files /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/Xilinx_Embedded_Design.bd
set_property used_in_implementation false [get_files -all /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/Xilinx_Embedded_Design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Xilinx_Embedded_Design_wrapper -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Xilinx_Embedded_Design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Xilinx_Embedded_Design_wrapper_utilization_synth.rpt -pb Xilinx_Embedded_Design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
