# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/hp/projects/vivado/zcu104_ug1209/Embedded_Design_Tutorial.srcs/sources_1/bd/Xilinx_Embedded_Design/ip/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0/Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xilinx_Embedded_Design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
